/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SegurancaRouteImport } from './routes/seguranca'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PainelIndexRouteImport } from './routes/painel/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as PainelSaldoRouteImport } from './routes/painel/saldo'
import { Route as PainelRecompensasRouteImport } from './routes/painel/recompensas'
import { Route as PainelRankingRouteImport } from './routes/painel/ranking'
import { Route as PainelPerfilRouteImport } from './routes/painel/perfil'
import { Route as PainelPagamentosRouteImport } from './routes/painel/pagamentos'
import { Route as PainelNotificacoesRouteImport } from './routes/painel/notificacoes'
import { Route as PainelMeusLancesRouteImport } from './routes/painel/meus-lances'
import { Route as PainelLanceAutomaticoRouteImport } from './routes/painel/lance-automatico'
import { Route as PainelFavoritosRouteImport } from './routes/painel/favoritos'
import { Route as PainelDocumentosRouteImport } from './routes/painel/documentos'
import { Route as PainelAtivosRouteImport } from './routes/painel/ativos'
import { Route as PainelArrematadosRouteImport } from './routes/painel/arrematados'
import { Route as LoteLotIdRouteImport } from './routes/lote.$lotId'
import { Route as LeilaoAuctionIdRouteImport } from './routes/leilao.$auctionId'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSoldLotsRouteImport } from './routes/admin/sold-lots'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSecurityRouteImport } from './routes/admin/security'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminPdfHistoryRouteImport } from './routes/admin/pdf-history'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminLotsRouteImport } from './routes/admin/lots'
import { Route as AdminInstitutionalRouteImport } from './routes/admin/institutional'
import { Route as AdminContractsRouteImport } from './routes/admin/contracts'
import { Route as AdminCaucaoRouteImport } from './routes/admin/caucao'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminBannersRouteImport } from './routes/admin/banners'
import { Route as AdminAuditLogsRouteImport } from './routes/admin/audit-logs'
import { Route as AdminAuditLiveRouteImport } from './routes/admin/audit-live'
import { Route as AdminAuditClosingsRouteImport } from './routes/admin/audit-closings'
import { Route as AdminAuctionsRouteImport } from './routes/admin/auctions'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as LeilaoAuctionIdLiveRouteImport } from './routes/leilao.$auctionId.live'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurancaRoute = SegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/painel/',
  path: '/painel/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelSaldoRoute = PainelSaldoRouteImport.update({
  id: '/painel/saldo',
  path: '/painel/saldo',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRecompensasRoute = PainelRecompensasRouteImport.update({
  id: '/painel/recompensas',
  path: '/painel/recompensas',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRankingRoute = PainelRankingRouteImport.update({
  id: '/painel/ranking',
  path: '/painel/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelPerfilRoute = PainelPerfilRouteImport.update({
  id: '/painel/perfil',
  path: '/painel/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelPagamentosRoute = PainelPagamentosRouteImport.update({
  id: '/painel/pagamentos',
  path: '/painel/pagamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelNotificacoesRoute = PainelNotificacoesRouteImport.update({
  id: '/painel/notificacoes',
  path: '/painel/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelMeusLancesRoute = PainelMeusLancesRouteImport.update({
  id: '/painel/meus-lances',
  path: '/painel/meus-lances',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelLanceAutomaticoRoute = PainelLanceAutomaticoRouteImport.update({
  id: '/painel/lance-automatico',
  path: '/painel/lance-automatico',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelFavoritosRoute = PainelFavoritosRouteImport.update({
  id: '/painel/favoritos',
  path: '/painel/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelDocumentosRoute = PainelDocumentosRouteImport.update({
  id: '/painel/documentos',
  path: '/painel/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelAtivosRoute = PainelAtivosRouteImport.update({
  id: '/painel/ativos',
  path: '/painel/ativos',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelArrematadosRoute = PainelArrematadosRouteImport.update({
  id: '/painel/arrematados',
  path: '/painel/arrematados',
  getParentRoute: () => rootRouteImport,
} as any)
const LoteLotIdRoute = LoteLotIdRouteImport.update({
  id: '/lote/$lotId',
  path: '/lote/$lotId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeilaoAuctionIdRoute = LeilaoAuctionIdRouteImport.update({
  id: '/leilao/$auctionId',
  path: '/leilao/$auctionId',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSoldLotsRoute = AdminSoldLotsRouteImport.update({
  id: '/admin/sold-lots',
  path: '/admin/sold-lots',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/admin/security',
  path: '/admin/security',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPdfHistoryRoute = AdminPdfHistoryRouteImport.update({
  id: '/admin/pdf-history',
  path: '/admin/pdf-history',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLotsRoute = AdminLotsRouteImport.update({
  id: '/admin/lots',
  path: '/admin/lots',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInstitutionalRoute = AdminInstitutionalRouteImport.update({
  id: '/admin/institutional',
  path: '/admin/institutional',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContractsRoute = AdminContractsRouteImport.update({
  id: '/admin/contracts',
  path: '/admin/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCaucaoRoute = AdminCaucaoRouteImport.update({
  id: '/admin/caucao',
  path: '/admin/caucao',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/admin/banners',
  path: '/admin/banners',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLiveRoute = AdminAuditLiveRouteImport.update({
  id: '/admin/audit-live',
  path: '/admin/audit-live',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditClosingsRoute = AdminAuditClosingsRouteImport.update({
  id: '/admin/audit-closings',
  path: '/admin/audit-closings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuctionsRoute = AdminAuctionsRouteImport.update({
  id: '/admin/auctions',
  path: '/admin/auctions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const LeilaoAuctionIdLiveRoute = LeilaoAuctionIdLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => LeilaoAuctionIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/entrar': typeof EntrarRoute
  '/privacidade': typeof PrivacidadeRoute
  '/seguranca': typeof SegurancaRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/auctions': typeof AdminAuctionsRoute
  '/admin/audit-closings': typeof AdminAuditClosingsRoute
  '/admin/audit-live': typeof AdminAuditLiveRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/caucao': typeof AdminCaucaoRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/institutional': typeof AdminInstitutionalRoute
  '/admin/lots': typeof AdminLotsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pdf-history': typeof AdminPdfHistoryRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sold-lots': typeof AdminSoldLotsRoute
  '/admin/users': typeof AdminUsersRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/leilao/$auctionId': typeof LeilaoAuctionIdRouteWithChildren
  '/lote/$lotId': typeof LoteLotIdRoute
  '/painel/arrematados': typeof PainelArrematadosRoute
  '/painel/ativos': typeof PainelAtivosRoute
  '/painel/documentos': typeof PainelDocumentosRoute
  '/painel/favoritos': typeof PainelFavoritosRoute
  '/painel/lance-automatico': typeof PainelLanceAutomaticoRoute
  '/painel/meus-lances': typeof PainelMeusLancesRoute
  '/painel/notificacoes': typeof PainelNotificacoesRoute
  '/painel/pagamentos': typeof PainelPagamentosRoute
  '/painel/perfil': typeof PainelPerfilRoute
  '/painel/ranking': typeof PainelRankingRoute
  '/painel/recompensas': typeof PainelRecompensasRoute
  '/painel/saldo': typeof PainelSaldoRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/admin/': typeof AdminIndexRoute
  '/painel/': typeof PainelIndexRoute
  '/leilao/$auctionId/live': typeof LeilaoAuctionIdLiveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/entrar': typeof EntrarRoute
  '/privacidade': typeof PrivacidadeRoute
  '/seguranca': typeof SegurancaRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/auctions': typeof AdminAuctionsRoute
  '/admin/audit-closings': typeof AdminAuditClosingsRoute
  '/admin/audit-live': typeof AdminAuditLiveRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/caucao': typeof AdminCaucaoRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/institutional': typeof AdminInstitutionalRoute
  '/admin/lots': typeof AdminLotsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pdf-history': typeof AdminPdfHistoryRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sold-lots': typeof AdminSoldLotsRoute
  '/admin/users': typeof AdminUsersRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/leilao/$auctionId': typeof LeilaoAuctionIdRouteWithChildren
  '/lote/$lotId': typeof LoteLotIdRoute
  '/painel/arrematados': typeof PainelArrematadosRoute
  '/painel/ativos': typeof PainelAtivosRoute
  '/painel/documentos': typeof PainelDocumentosRoute
  '/painel/favoritos': typeof PainelFavoritosRoute
  '/painel/lance-automatico': typeof PainelLanceAutomaticoRoute
  '/painel/meus-lances': typeof PainelMeusLancesRoute
  '/painel/notificacoes': typeof PainelNotificacoesRoute
  '/painel/pagamentos': typeof PainelPagamentosRoute
  '/painel/perfil': typeof PainelPerfilRoute
  '/painel/ranking': typeof PainelRankingRoute
  '/painel/recompensas': typeof PainelRecompensasRoute
  '/painel/saldo': typeof PainelSaldoRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/admin': typeof AdminIndexRoute
  '/painel': typeof PainelIndexRoute
  '/leilao/$auctionId/live': typeof LeilaoAuctionIdLiveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/entrar': typeof EntrarRoute
  '/privacidade': typeof PrivacidadeRoute
  '/seguranca': typeof SegurancaRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/auctions': typeof AdminAuctionsRoute
  '/admin/audit-closings': typeof AdminAuditClosingsRoute
  '/admin/audit-live': typeof AdminAuditLiveRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/caucao': typeof AdminCaucaoRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/institutional': typeof AdminInstitutionalRoute
  '/admin/lots': typeof AdminLotsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pdf-history': typeof AdminPdfHistoryRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sold-lots': typeof AdminSoldLotsRoute
  '/admin/users': typeof AdminUsersRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/leilao/$auctionId': typeof LeilaoAuctionIdRouteWithChildren
  '/lote/$lotId': typeof LoteLotIdRoute
  '/painel/arrematados': typeof PainelArrematadosRoute
  '/painel/ativos': typeof PainelAtivosRoute
  '/painel/documentos': typeof PainelDocumentosRoute
  '/painel/favoritos': typeof PainelFavoritosRoute
  '/painel/lance-automatico': typeof PainelLanceAutomaticoRoute
  '/painel/meus-lances': typeof PainelMeusLancesRoute
  '/painel/notificacoes': typeof PainelNotificacoesRoute
  '/painel/pagamentos': typeof PainelPagamentosRoute
  '/painel/perfil': typeof PainelPerfilRoute
  '/painel/ranking': typeof PainelRankingRoute
  '/painel/recompensas': typeof PainelRecompensasRoute
  '/painel/saldo': typeof PainelSaldoRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/admin/': typeof AdminIndexRoute
  '/painel/': typeof PainelIndexRoute
  '/leilao/$auctionId/live': typeof LeilaoAuctionIdLiveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/como-funciona'
    | '/contato'
    | '/entrar'
    | '/privacidade'
    | '/seguranca'
    | '/sobre'
    | '/termos'
    | '/admin/analytics'
    | '/admin/auctions'
    | '/admin/audit-closings'
    | '/admin/audit-live'
    | '/admin/audit-logs'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/caucao'
    | '/admin/contracts'
    | '/admin/institutional'
    | '/admin/lots'
    | '/admin/payments'
    | '/admin/pdf-history'
    | '/admin/reports'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/sold-lots'
    | '/admin/users'
    | '/categoria/$slug'
    | '/leilao/$auctionId'
    | '/lote/$lotId'
    | '/painel/arrematados'
    | '/painel/ativos'
    | '/painel/documentos'
    | '/painel/favoritos'
    | '/painel/lance-automatico'
    | '/painel/meus-lances'
    | '/painel/notificacoes'
    | '/painel/pagamentos'
    | '/painel/perfil'
    | '/painel/ranking'
    | '/painel/recompensas'
    | '/painel/saldo'
    | '/sitemap/xml'
    | '/admin/'
    | '/painel/'
    | '/leilao/$auctionId/live'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/como-funciona'
    | '/contato'
    | '/entrar'
    | '/privacidade'
    | '/seguranca'
    | '/sobre'
    | '/termos'
    | '/admin/analytics'
    | '/admin/auctions'
    | '/admin/audit-closings'
    | '/admin/audit-live'
    | '/admin/audit-logs'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/caucao'
    | '/admin/contracts'
    | '/admin/institutional'
    | '/admin/lots'
    | '/admin/payments'
    | '/admin/pdf-history'
    | '/admin/reports'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/sold-lots'
    | '/admin/users'
    | '/categoria/$slug'
    | '/leilao/$auctionId'
    | '/lote/$lotId'
    | '/painel/arrematados'
    | '/painel/ativos'
    | '/painel/documentos'
    | '/painel/favoritos'
    | '/painel/lance-automatico'
    | '/painel/meus-lances'
    | '/painel/notificacoes'
    | '/painel/pagamentos'
    | '/painel/perfil'
    | '/painel/ranking'
    | '/painel/recompensas'
    | '/painel/saldo'
    | '/sitemap/xml'
    | '/admin'
    | '/painel'
    | '/leilao/$auctionId/live'
  id:
    | '__root__'
    | '/'
    | '/como-funciona'
    | '/contato'
    | '/entrar'
    | '/privacidade'
    | '/seguranca'
    | '/sobre'
    | '/termos'
    | '/admin/analytics'
    | '/admin/auctions'
    | '/admin/audit-closings'
    | '/admin/audit-live'
    | '/admin/audit-logs'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/caucao'
    | '/admin/contracts'
    | '/admin/institutional'
    | '/admin/lots'
    | '/admin/payments'
    | '/admin/pdf-history'
    | '/admin/reports'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/sold-lots'
    | '/admin/users'
    | '/categoria/$slug'
    | '/leilao/$auctionId'
    | '/lote/$lotId'
    | '/painel/arrematados'
    | '/painel/ativos'
    | '/painel/documentos'
    | '/painel/favoritos'
    | '/painel/lance-automatico'
    | '/painel/meus-lances'
    | '/painel/notificacoes'
    | '/painel/pagamentos'
    | '/painel/perfil'
    | '/painel/ranking'
    | '/painel/recompensas'
    | '/painel/saldo'
    | '/sitemap/xml'
    | '/admin/'
    | '/painel/'
    | '/leilao/$auctionId/live'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ContatoRoute: typeof ContatoRoute
  EntrarRoute: typeof EntrarRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SegurancaRoute: typeof SegurancaRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuctionsRoute: typeof AdminAuctionsRoute
  AdminAuditClosingsRoute: typeof AdminAuditClosingsRoute
  AdminAuditLiveRoute: typeof AdminAuditLiveRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCaucaoRoute: typeof AdminCaucaoRoute
  AdminContractsRoute: typeof AdminContractsRoute
  AdminInstitutionalRoute: typeof AdminInstitutionalRoute
  AdminLotsRoute: typeof AdminLotsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPdfHistoryRoute: typeof AdminPdfHistoryRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSoldLotsRoute: typeof AdminSoldLotsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  LeilaoAuctionIdRoute: typeof LeilaoAuctionIdRouteWithChildren
  LoteLotIdRoute: typeof LoteLotIdRoute
  PainelArrematadosRoute: typeof PainelArrematadosRoute
  PainelAtivosRoute: typeof PainelAtivosRoute
  PainelDocumentosRoute: typeof PainelDocumentosRoute
  PainelFavoritosRoute: typeof PainelFavoritosRoute
  PainelLanceAutomaticoRoute: typeof PainelLanceAutomaticoRoute
  PainelMeusLancesRoute: typeof PainelMeusLancesRoute
  PainelNotificacoesRoute: typeof PainelNotificacoesRoute
  PainelPagamentosRoute: typeof PainelPagamentosRoute
  PainelPerfilRoute: typeof PainelPerfilRoute
  PainelRankingRoute: typeof PainelRankingRoute
  PainelRecompensasRoute: typeof PainelRecompensasRoute
  PainelSaldoRoute: typeof PainelSaldoRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  AdminIndexRoute: typeof AdminIndexRoute
  PainelIndexRoute: typeof PainelIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguranca': {
      id: '/seguranca'
      path: '/seguranca'
      fullPath: '/seguranca'
      preLoaderRoute: typeof SegurancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/': {
      id: '/painel/'
      path: '/painel'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/saldo': {
      id: '/painel/saldo'
      path: '/painel/saldo'
      fullPath: '/painel/saldo'
      preLoaderRoute: typeof PainelSaldoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/recompensas': {
      id: '/painel/recompensas'
      path: '/painel/recompensas'
      fullPath: '/painel/recompensas'
      preLoaderRoute: typeof PainelRecompensasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/ranking': {
      id: '/painel/ranking'
      path: '/painel/ranking'
      fullPath: '/painel/ranking'
      preLoaderRoute: typeof PainelRankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/perfil': {
      id: '/painel/perfil'
      path: '/painel/perfil'
      fullPath: '/painel/perfil'
      preLoaderRoute: typeof PainelPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/pagamentos': {
      id: '/painel/pagamentos'
      path: '/painel/pagamentos'
      fullPath: '/painel/pagamentos'
      preLoaderRoute: typeof PainelPagamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/notificacoes': {
      id: '/painel/notificacoes'
      path: '/painel/notificacoes'
      fullPath: '/painel/notificacoes'
      preLoaderRoute: typeof PainelNotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/meus-lances': {
      id: '/painel/meus-lances'
      path: '/painel/meus-lances'
      fullPath: '/painel/meus-lances'
      preLoaderRoute: typeof PainelMeusLancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/lance-automatico': {
      id: '/painel/lance-automatico'
      path: '/painel/lance-automatico'
      fullPath: '/painel/lance-automatico'
      preLoaderRoute: typeof PainelLanceAutomaticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/favoritos': {
      id: '/painel/favoritos'
      path: '/painel/favoritos'
      fullPath: '/painel/favoritos'
      preLoaderRoute: typeof PainelFavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/documentos': {
      id: '/painel/documentos'
      path: '/painel/documentos'
      fullPath: '/painel/documentos'
      preLoaderRoute: typeof PainelDocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/ativos': {
      id: '/painel/ativos'
      path: '/painel/ativos'
      fullPath: '/painel/ativos'
      preLoaderRoute: typeof PainelAtivosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/arrematados': {
      id: '/painel/arrematados'
      path: '/painel/arrematados'
      fullPath: '/painel/arrematados'
      preLoaderRoute: typeof PainelArrematadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lote/$lotId': {
      id: '/lote/$lotId'
      path: '/lote/$lotId'
      fullPath: '/lote/$lotId'
      preLoaderRoute: typeof LoteLotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leilao/$auctionId': {
      id: '/leilao/$auctionId'
      path: '/leilao/$auctionId'
      fullPath: '/leilao/$auctionId'
      preLoaderRoute: typeof LeilaoAuctionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sold-lots': {
      id: '/admin/sold-lots'
      path: '/admin/sold-lots'
      fullPath: '/admin/sold-lots'
      preLoaderRoute: typeof AdminSoldLotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/admin/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pdf-history': {
      id: '/admin/pdf-history'
      path: '/admin/pdf-history'
      fullPath: '/admin/pdf-history'
      preLoaderRoute: typeof AdminPdfHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/lots': {
      id: '/admin/lots'
      path: '/admin/lots'
      fullPath: '/admin/lots'
      preLoaderRoute: typeof AdminLotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/institutional': {
      id: '/admin/institutional'
      path: '/admin/institutional'
      fullPath: '/admin/institutional'
      preLoaderRoute: typeof AdminInstitutionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contracts': {
      id: '/admin/contracts'
      path: '/admin/contracts'
      fullPath: '/admin/contracts'
      preLoaderRoute: typeof AdminContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/caucao': {
      id: '/admin/caucao'
      path: '/admin/caucao'
      fullPath: '/admin/caucao'
      preLoaderRoute: typeof AdminCaucaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/admin/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-live': {
      id: '/admin/audit-live'
      path: '/admin/audit-live'
      fullPath: '/admin/audit-live'
      preLoaderRoute: typeof AdminAuditLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-closings': {
      id: '/admin/audit-closings'
      path: '/admin/audit-closings'
      fullPath: '/admin/audit-closings'
      preLoaderRoute: typeof AdminAuditClosingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/auctions': {
      id: '/admin/auctions'
      path: '/admin/auctions'
      fullPath: '/admin/auctions'
      preLoaderRoute: typeof AdminAuctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leilao/$auctionId/live': {
      id: '/leilao/$auctionId/live'
      path: '/live'
      fullPath: '/leilao/$auctionId/live'
      preLoaderRoute: typeof LeilaoAuctionIdLiveRouteImport
      parentRoute: typeof LeilaoAuctionIdRoute
    }
  }
}

interface LeilaoAuctionIdRouteChildren {
  LeilaoAuctionIdLiveRoute: typeof LeilaoAuctionIdLiveRoute
}

const LeilaoAuctionIdRouteChildren: LeilaoAuctionIdRouteChildren = {
  LeilaoAuctionIdLiveRoute: LeilaoAuctionIdLiveRoute,
}

const LeilaoAuctionIdRouteWithChildren = LeilaoAuctionIdRoute._addFileChildren(
  LeilaoAuctionIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ContatoRoute: ContatoRoute,
  EntrarRoute: EntrarRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SegurancaRoute: SegurancaRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuctionsRoute: AdminAuctionsRoute,
  AdminAuditClosingsRoute: AdminAuditClosingsRoute,
  AdminAuditLiveRoute: AdminAuditLiveRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCaucaoRoute: AdminCaucaoRoute,
  AdminContractsRoute: AdminContractsRoute,
  AdminInstitutionalRoute: AdminInstitutionalRoute,
  AdminLotsRoute: AdminLotsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPdfHistoryRoute: AdminPdfHistoryRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSoldLotsRoute: AdminSoldLotsRoute,
  AdminUsersRoute: AdminUsersRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  LeilaoAuctionIdRoute: LeilaoAuctionIdRouteWithChildren,
  LoteLotIdRoute: LoteLotIdRoute,
  PainelArrematadosRoute: PainelArrematadosRoute,
  PainelAtivosRoute: PainelAtivosRoute,
  PainelDocumentosRoute: PainelDocumentosRoute,
  PainelFavoritosRoute: PainelFavoritosRoute,
  PainelLanceAutomaticoRoute: PainelLanceAutomaticoRoute,
  PainelMeusLancesRoute: PainelMeusLancesRoute,
  PainelNotificacoesRoute: PainelNotificacoesRoute,
  PainelPagamentosRoute: PainelPagamentosRoute,
  PainelPerfilRoute: PainelPerfilRoute,
  PainelRankingRoute: PainelRankingRoute,
  PainelRecompensasRoute: PainelRecompensasRoute,
  PainelSaldoRoute: PainelSaldoRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  AdminIndexRoute: AdminIndexRoute,
  PainelIndexRoute: PainelIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
